version: '3.8'

services:
  app:
    image: basic-yii2-app_app:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"  # Optional if you want to access app directly
    networks:
      - yii2-net
    volumes:
      - ./runtime:/var/www/html/runtime
      - ./web/assets:/var/www/html/web/assets

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - yii2-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  yii2-net:
    driver: overlay

